---

- name: Update elasticsearch to allow localhost access
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: 'networks.host:'
    line: 'networks.host: {{ es_host }}'

- name: Setup elasticsearch port
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: 'http.host:'
    line: 'http.host: {{ es_port }}'

- name: Start elasticsearch
  systemd:
    name: elasticsearch
    state: restarted
    enabled: yes