---

- name: Allow localhost kibana access
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: 'server.host:'
    line: 'server.host: 127.0.0.1'

- name: Set port for kibana
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: 'server.port:'
    line: 'server.port: 5601'

- name: Set elasticsearch url in kibana config
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: 'elasticsearch.url:'
    line: 'elasticsearch.url: "http://0.0.0.0:9200"'

- name: Restart kibana
  systemd:
    name: kibana
    state: restarted
    enabled: yes