---

- name: Install Kibana
  apt:
    name: kibana
    update_cache: yes

- name: Allow localhost kibana access
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: 'server.host:'
    line: 'server.host: 127.0.0.1'

- name: Start kibana
  systemd:
    name: kibana
    state: started
    enabled: yes